# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo Logging in to Azure...
    az login --service-principal -u $(clientId) -p $(clientSecret) --tenant $(tenantId)
  displayName: 'Login to Azure'

- script: |
    echo Building Docker image...
    docker build -t communityplatform.azurecr.io/backend:$(Build.BuildId) .
    echo Pushing Docker image to container registry...
    docker push communityplatform.azurecr.io/backend:$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'c9f19a68-3099-4c5f-876e-4d3dfdc55073'
    appName: 'CommunityPlatform'
    containers: 'communityplatform.azurecr.io/backend:$(Build.BuildId)'
  displayName: 'Deploy to Azure Web App'
