trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  clientId: '3795f7a1-23d7-4a03-8270-2aabf7e63704'
  clientSecret: $(clientSecret)
  tenantId: $(tenantId)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo Logging in to Azure...
    az login --service-principal -u $(clientId) -p $(clientSecret) --tenant $(tenantId)
  displayName: 'Login to Azure'

- script: |
    echo Building Docker image...
    docker build -t communityplatform.azurecr.io/backend:$(Build.BuildId) .
    echo Pushing Docker image to container registry...
    docker push communityplatform.azurecr.io/backend:$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'c9f19a68-3099-4c5f-876e-4d3dfdc55073'
    appName: 'CommunityPlatform'
    containers: 'communityplatform.azurecr.io/backend:$(Build.BuildId)'
    healthProbePath: '/healthcheck'
  displayName: 'Deploy to Azure Web App'
